name: Email Action Example

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: 22f3000814@ds.study.iitm.ac.in
        run: echo "Hello, world!"
